name: Lambda@Edge CI
on:
  pull_request:
    paths:
      - "edge-lambdas/**"
      - ".github/workflows/edge-lambda-ci.yml"

concurrency:
  group: edge-lambda-ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: edge-lambdas

jobs:
  ci:
    name: Check Lambda@Edge Functions
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: edge-lambdas/yarn.lock

      - run: yarn --frozen-lockfile
      - run: make lint
      - run: make test
      - run: make build

      - name: Check if built version was committed
        run: |
          git diff --quiet --exit-code || (echo "::error::You forgot to commit the built lambdas, run 'make' locally" && exit 1)
