name: "Semantic Release"

on:
  push:
    branches: [main]

jobs:
  release:
    name: Run Semantic Release Action
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false

      # Sets up SSH (Deploy) key which allows authoring commits directly on main branch
      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SEMANTIC_RELEASE_DEPLOYER_PRIVATE_KEY }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
